language: go

go:
- 1.9

cache:
  directories:
  - vendor

before_install:
- go get -u github.com/golang/dep/cmd/dep

install:
- export GOBIN="$GOPATH/bin"
- export PATH="$PATH:$GOBIN"
- make dep
- make cmds

script:
- make ci-test
